[login] Fixed user creation.
User: use Configuration::loadJson.
NoSuchUserException: must inherit from AgoraException.
Configuration: renamed directory, forgot to change here.